#%RAML 1.0

title:       Pagination Prototype
description: API returns 243 country records (paged)
baseUri:     http://${app.host}:${app.port}/api/v1/countries

mediaType: application/json
version: v1

/health:
  description: Dead simple health check
  get:
    responses:
      200:
        body:
          application/json:
            example: !include examples/success-health.json

/:
  get:
    description: Retrieve the country records. #http://localhost:8081/api/v1/countries?startItem=1&maxItems=20
    queryParameters:
      startItem:
        example: 1
        type: number
        format: int
        required: false
      maxItemCount:
        example: 20
        type: number
        format: int
        required: false
    responses:
      200:
        body:
          application/json:
            example: !include examples/countries.json
